OpenShift Virtualization Roadshowへようこそ！

== 日本語化の方法
ラボ環境のbastionへSSHログイン後、以下のコマンドで翻訳スクリプトを実行ください。

[source,bash,role=execute,subs="attributes"]
----
curl -sSL https://gist.githubusercontent.com/KaitoInaba/1594964e92bb1c0ded7609acdb6ed2f6/raw/cd4a204cb929b2dcb9a75916ab43ceb42c1901d0/translation.sh | bash
----

== はじめに
このリポジトリーは、Red Hat アソシエイツが世界中の顧客や関係者に提供する OpenShift 仮想化ロードショーのラボガイドをホストしています。

これは、Red Hat Demo Platform (RHDP) チームが提供する Showroom ラボ環境で動作するように設計されています。

このロードショーイベントは、Red Hat OpenShift Virtualization を実際に体験していただくために企画されました。

OpenShift Virtualization は、最新の Kubernetes ベースのインフラストラクチャ上に仮想マシンを導入することを可能にします。OpenShift Virtualization は、新しいアプリケーションの開発と提供、および既存のアプリケーションのモダナイゼーションを可能にし、仮想マシン、コンテナ、サーバーレス機能で構成されるアプリケーションを作成できます。

このイベントでは、仮想管理者が日々のワークフローでよく遭遇する多くの一般的な管理活動について探求します。

== ロードショーに参加することで最も恩恵を受けるのは誰ですか？

*仮想マシン管理者* -- OpenShift Virtualizationで仮想ゲストの日々の管理を担当している方。このようなユーザーは、仮想ゲストのプロビジョニング、ゲストとその中で実行されるアプリケーションの日々の管理を担当することが多いでしょう。

*仮想インフラストラクチャ管理者* -- OpenShift Virtualizationソリューションをホストする物理インフラストラクチャの責任者。これらのユーザーは、実行中の仮想マシンの日々の運用に影響を与える、環境に対する物理ハードウェア、ストレージ、ネットワークの変更に責任を負います。


== ロードショーでカバーされる内容は？

ロードショーで扱う主な内容は以下の8つです:

* _仮想マシンの管理_ ：仮想マシンの作成、割り当てリソースの変更など、仮想マシン管理の基本について説明します。

* _既存の仮想マシンの移行_: このセクションでは、Migration Toolkit for Virtualization (MTV) を使用して、既存の VMware vSphere 環境から OpenShift Virtualization へ仮想マシンを移行します。

* _ベアメタル・インフラストラクチャの管理_: このセクションでは、管理者が仮想化ワークロードをホストするために追加のワーカーノードを追加することで OpenShift 環境を拡張する方法を学びます。

* _ストレージ管理_: 多くの管理者に馴染みのあるストレージのパラダイムが OpenShift Virtualization で変わります。このセクションでは、仮想マシンのストレージ管理に関連する多くのアクションを探ります。

* _仮想マシンのバックアップとリカバリ_: このユニットでは、仮想マシンの外部サイトへのバックアップと災害時のリストアに関する追加コンセプトを紹介し、デモンストレーションを行います。

* _ネットワーク管理_: デフォルトでは、VM は OpenShift のポッドネットワークに接続されています。このセクションでは、新しい L2 ネットワークマッピングの作成と、複数のネットワークに対するマイクロセグメンテーションポリシーの設定について説明します。

* _テンプレートとインスタンスタイプの管理_: 仮想マシンのデプロイを効率化するために、管理者はデプロイ操作を容易にするために、Templateを作成したり、InstanceTypeを定義したりすることがよくあります。このセクションでは、これらのプロセスについて説明します。

* _仮想マシンとアプリケーションの操作_: このセクションでは、インポートした仮想マシンを使用して、ロードバランサーのセットアップや、サービスやルートを通じて仮想マシンがホストするアプリケーションの公開など、2日目のアクティビティをいくつか実行します。

== バージョン情報

この OpenShift 仮想化ロードショーのエディションは、以下のソフトウェア・バージョンを使用して開発されています：

* Red Hat OpenShift 4.16.5
* Red Hat OpenShift Virtualization 4.16.1
* Red Hat OpenShift Data Foundation 4.16.0
* Red Hat OADP 1.4.0
* Red Hat Migration Toolkit for Virtual Machines 2.6.3

(2024年8月16日現在の情報です)
